#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JamnationApp.Droid.Resource", IsApplication=true)]

namespace JamnationApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::JamnationApp.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::JamnationApp.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::JamnationApp.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::JamnationApp.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::JamnationApp.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::JamnationApp.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::JamnationApp.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::JamnationApp.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::JamnationApp.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::JamnationApp.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::JamnationApp.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::JamnationApp.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::JamnationApp.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::JamnationApp.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::JamnationApp.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::JamnationApp.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::JamnationApp.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::JamnationApp.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::JamnationApp.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::JamnationApp.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::JamnationApp.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::JamnationApp.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::JamnationApp.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::JamnationApp.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::JamnationApp.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circleColor = global::JamnationApp.Droid.Resource.Attribute.circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circularProgressBarStyle = global::JamnationApp.Droid.Resource.Attribute.circularProgressBarStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_gravity = global::JamnationApp.Droid.Resource.Attribute.circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate = global::JamnationApp.Droid.Resource.Attribute.circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate_interval = global::JamnationApp.Droid.Resource.Attribute.circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_marker_progress = global::JamnationApp.Droid.Resource.Attribute.circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress = global::JamnationApp.Droid.Resource.Attribute.circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_background_color = global::JamnationApp.Droid.Resource.Attribute.circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_color = global::JamnationApp.Droid.Resource.Attribute.circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_stroke_width = global::JamnationApp.Droid.Resource.Attribute.circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate = global::JamnationApp.Droid.Resource.Attribute.indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate_interval = global::JamnationApp.Droid.Resource.Attribute.indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.innerSize = global::JamnationApp.Droid.Resource.Attribute.innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.max = global::JamnationApp.Droid.Resource.Attribute.max;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinned = global::JamnationApp.Droid.Resource.Attribute.pinned;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinnedDrawable = global::JamnationApp.Droid.Resource.Attribute.pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progress = global::JamnationApp.Droid.Resource.Attribute.progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressButtonStyle = global::JamnationApp.Droid.Resource.Attribute.progressButtonStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressColor = global::JamnationApp.Droid.Resource.Attribute.progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.shadowDrawable = global::JamnationApp.Droid.Resource.Attribute.shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.unpinnedDrawable = global::JamnationApp.Droid.Resource.Attribute.unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_circle_color = global::JamnationApp.Droid.Resource.Color.progress_default_circle_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_progress_color = global::JamnationApp.Droid.Resource.Color.progress_default_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_dark = global::JamnationApp.Droid.Resource.Color.refractored_background_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_dark = global::JamnationApp.Droid.Resource.Color.refractored_background_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_light = global::JamnationApp.Droid.Resource.Color.refractored_background_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_light = global::JamnationApp.Droid.Resource.Color.refractored_background_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark = global::JamnationApp.Droid.Resource.Color.refractored_bright_foreground_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark_disabled = global::JamnationApp.Droid.Resource.Color.refractored_bright_foreground_dark_disabled;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_dark = global::JamnationApp.Droid.Resource.Color.refractored_bright_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_light = global::JamnationApp.Droid.Resource.Color.refractored_bright_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_dark = global::JamnationApp.Droid.Resource.Color.refractored_bright_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_light = global::JamnationApp.Droid.Resource.Color.refractored_bright_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_light = global::JamnationApp.Droid.Resource.Color.refractored_bright_foreground_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_dark = global::JamnationApp.Droid.Resource.Color.refractored_dim_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_light = global::JamnationApp.Droid.Resource.Color.refractored_dim_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_dark = global::JamnationApp.Droid.Resource.Color.refractored_dim_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_light = global::JamnationApp.Droid.Resource.Color.refractored_dim_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_dark = global::JamnationApp.Droid.Resource.Color.refractored_highlighted_text_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_light = global::JamnationApp.Droid.Resource.Color.refractored_highlighted_text_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_dark = global::JamnationApp.Droid.Resource.Color.refractored_hint_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_light = global::JamnationApp.Droid.Resource.Color.refractored_hint_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_bright = global::JamnationApp.Droid.Resource.Color.refractored_holo_blue_bright;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_dark = global::JamnationApp.Droid.Resource.Color.refractored_holo_blue_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_light = global::JamnationApp.Droid.Resource.Color.refractored_holo_blue_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_dark = global::JamnationApp.Droid.Resource.Color.refractored_holo_green_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_light = global::JamnationApp.Droid.Resource.Color.refractored_holo_green_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_dark = global::JamnationApp.Droid.Resource.Color.refractored_holo_orange_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_light = global::JamnationApp.Droid.Resource.Color.refractored_holo_orange_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_purple = global::JamnationApp.Droid.Resource.Color.refractored_holo_purple;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_dark = global::JamnationApp.Droid.Resource.Color.refractored_holo_red_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_light = global::JamnationApp.Droid.Resource.Color.refractored_holo_red_light;
			global::com.refractored.monodroidtoolkit.Resource.Dimension.progress_inner_size = global::JamnationApp.Droid.Resource.Dimension.progress_inner_size;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_pinned = global::JamnationApp.Droid.Resource.Drawable.pin_progress_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_shadow = global::JamnationApp.Droid.Resource.Drawable.pin_progress_shadow;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_unpinned = global::JamnationApp.Droid.Resource.Drawable.pin_progress_unpinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_normal_holo = global::JamnationApp.Droid.Resource.Drawable.scrubber_control_normal_holo;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_pressed_holo = global::JamnationApp.Droid.Resource.Drawable.scrubber_control_pressed_holo;
			global::com.refractored.monodroidtoolkit.Resource.Id.bottom = global::JamnationApp.Droid.Resource.Id.bottom;
			global::com.refractored.monodroidtoolkit.Resource.Id.center = global::JamnationApp.Droid.Resource.Id.center;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_horizontal = global::JamnationApp.Droid.Resource.Id.center_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_vertical = global::JamnationApp.Droid.Resource.Id.center_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip = global::JamnationApp.Droid.Resource.Id.clip;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_horizontal = global::JamnationApp.Droid.Resource.Id.clip_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_vertical = global::JamnationApp.Droid.Resource.Id.clip_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.end = global::JamnationApp.Droid.Resource.Id.end;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill = global::JamnationApp.Droid.Resource.Id.fill;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_horizontal = global::JamnationApp.Droid.Resource.Id.fill_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_vertical = global::JamnationApp.Droid.Resource.Id.fill_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.left = global::JamnationApp.Droid.Resource.Id.left;
			global::com.refractored.monodroidtoolkit.Resource.Id.right = global::JamnationApp.Droid.Resource.Id.right;
			global::com.refractored.monodroidtoolkit.Resource.Id.start = global::JamnationApp.Droid.Resource.Id.start;
			global::com.refractored.monodroidtoolkit.Resource.Id.top = global::JamnationApp.Droid.Resource.Id.top;
			global::com.refractored.monodroidtoolkit.Resource.Integer.circular_indeterminent_interval = global::JamnationApp.Droid.Resource.Integer.circular_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Integer.progressbutton_indeterminent_interval = global::JamnationApp.Droid.Resource.Integer.progressbutton_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBar = global::JamnationApp.Droid.Resource.Style.CircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBarLight = global::JamnationApp.Droid.Resource.Style.CircularProgressBarLight;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton = global::JamnationApp.Droid.Resource.Style.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton_Pin = global::JamnationApp.Droid.Resource.Style.ProgressButton_Pin;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar = global::JamnationApp.Droid.Resource.Styleable.HoloCircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_gravity = global::JamnationApp.Droid.Resource.Styleable.HoloCircularProgressBar_circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate = global::JamnationApp.Droid.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval = global::JamnationApp.Droid.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress = global::JamnationApp.Droid.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress = global::JamnationApp.Droid.Resource.Styleable.HoloCircularProgressBar_circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color = global::JamnationApp.Droid.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_color = global::JamnationApp.Droid.Resource.Styleable.HoloCircularProgressBar_circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width = global::JamnationApp.Droid.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton = global::JamnationApp.Droid.Resource.Styleable.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_clickable = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_android_clickable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_focusable = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_android_focusable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_selectableItemBackground = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_android_selectableItemBackground;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_circleColor = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate_interval = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_innerSize = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_max = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_max;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinned = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinnedDrawable = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progress = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progressColor = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_shadowDrawable = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_unpinnedDrawable = global::JamnationApp.Droid.Resource.Styleable.ProgressButton_unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme = global::JamnationApp.Droid.Resource.Styleable.Theme;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme_circularProgressBarStyle = global::JamnationApp.Droid.Resource.Styleable.Theme_circularProgressBarStyle;
			global::ModernHttpClient.Resource.String.library_name = global::JamnationApp.Droid.Resource.String.library_name;
			global::Splat.Resource.String.library_name = global::JamnationApp.Droid.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::JamnationApp.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::JamnationApp.Droid.Resource.String.Hello;
			global::XLabs.Forms.Droid.Resource.Boolean.abc_action_bar_embed_tabs = global::JamnationApp.Droid.Resource.Boolean.abc_action_bar_embed_tabs;
			global::XLabs.Forms.Droid.Resource.Color.calendar_active_month_bg = global::JamnationApp.Droid.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_bg = global::JamnationApp.Droid.Resource.Color.calendar_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_divider = global::JamnationApp.Droid.Resource.Color.calendar_divider;
			global::XLabs.Forms.Droid.Resource.Color.calendar_highlighted_day_bg = global::JamnationApp.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_inactive_month_bg = global::JamnationApp.Droid.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_selected_day_bg = global::JamnationApp.Droid.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_selected_range_bg = global::JamnationApp.Droid.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_active = global::JamnationApp.Droid.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_inactive = global::JamnationApp.Droid.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_selected = global::JamnationApp.Droid.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_selector = global::JamnationApp.Droid.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_unselectable = global::JamnationApp.Droid.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Droid.Resource.Color.primary_text_default_material_dark = global::JamnationApp.Droid.Resource.Color.primary_text_default_material_dark;
			global::XLabs.Forms.Droid.Resource.Color.ripple_material_light = global::JamnationApp.Droid.Resource.Color.ripple_material_light;
			global::XLabs.Forms.Droid.Resource.Color.secondary_text_default_material_dark = global::JamnationApp.Droid.Resource.Color.secondary_text_default_material_dark;
			global::XLabs.Forms.Droid.Resource.Color.secondary_text_default_material_light = global::JamnationApp.Droid.Resource.Color.secondary_text_default_material_light;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_day_headers_paddingbottom = global::JamnationApp.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_month_title_bottommargin = global::JamnationApp.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_month_topmargin = global::JamnationApp.Droid.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_text_medium = global::JamnationApp.Droid.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_text_small = global::JamnationApp.Droid.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Droid.Resource.Dimension.notification_large_icon_height = global::JamnationApp.Droid.Resource.Dimension.notification_large_icon_height;
			global::XLabs.Forms.Droid.Resource.Dimension.notification_large_icon_width = global::JamnationApp.Droid.Resource.Dimension.notification_large_icon_width;
			global::XLabs.Forms.Droid.Resource.Dimension.notification_subtext_size = global::JamnationApp.Droid.Resource.Dimension.notification_subtext_size;
			global::XLabs.Forms.Droid.Resource.Drawable.ad16 = global::JamnationApp.Droid.Resource.Drawable.ad16;
			global::XLabs.Forms.Droid.Resource.Drawable.calendar_bg_selector = global::JamnationApp.Droid.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Droid.Resource.Drawable.notification_template_icon_bg = global::JamnationApp.Droid.Resource.Drawable.notification_template_icon_bg;
			global::XLabs.Forms.Droid.Resource.Id.action0 = global::JamnationApp.Droid.Resource.Id.action0;
			global::XLabs.Forms.Droid.Resource.Id.action_divider = global::JamnationApp.Droid.Resource.Id.action_divider;
			global::XLabs.Forms.Droid.Resource.Id.bottom = global::JamnationApp.Droid.Resource.Id.bottom;
			global::XLabs.Forms.Droid.Resource.Id.calendar_grid = global::JamnationApp.Droid.Resource.Id.calendar_grid;
			global::XLabs.Forms.Droid.Resource.Id.calendar_view = global::JamnationApp.Droid.Resource.Id.calendar_view;
			global::XLabs.Forms.Droid.Resource.Id.calendarr_pager = global::JamnationApp.Droid.Resource.Id.calendarr_pager;
			global::XLabs.Forms.Droid.Resource.Id.cancel_action = global::JamnationApp.Droid.Resource.Id.cancel_action;
			global::XLabs.Forms.Droid.Resource.Id.center = global::JamnationApp.Droid.Resource.Id.center;
			global::XLabs.Forms.Droid.Resource.Id.center_horizontal = global::JamnationApp.Droid.Resource.Id.center_horizontal;
			global::XLabs.Forms.Droid.Resource.Id.center_vertical = global::JamnationApp.Droid.Resource.Id.center_vertical;
			global::XLabs.Forms.Droid.Resource.Id.chronometer = global::JamnationApp.Droid.Resource.Id.chronometer;
			global::XLabs.Forms.Droid.Resource.Id.clip_horizontal = global::JamnationApp.Droid.Resource.Id.clip_horizontal;
			global::XLabs.Forms.Droid.Resource.Id.clip_vertical = global::JamnationApp.Droid.Resource.Id.clip_vertical;
			global::XLabs.Forms.Droid.Resource.Id.end = global::JamnationApp.Droid.Resource.Id.end;
			global::XLabs.Forms.Droid.Resource.Id.end_padder = global::JamnationApp.Droid.Resource.Id.end_padder;
			global::XLabs.Forms.Droid.Resource.Id.fill = global::JamnationApp.Droid.Resource.Id.fill;
			global::XLabs.Forms.Droid.Resource.Id.fill_horizontal = global::JamnationApp.Droid.Resource.Id.fill_horizontal;
			global::XLabs.Forms.Droid.Resource.Id.fill_vertical = global::JamnationApp.Droid.Resource.Id.fill_vertical;
			global::XLabs.Forms.Droid.Resource.Id.icon = global::JamnationApp.Droid.Resource.Id.icon;
			global::XLabs.Forms.Droid.Resource.Id.info = global::JamnationApp.Droid.Resource.Id.info;
			global::XLabs.Forms.Droid.Resource.Id.left = global::JamnationApp.Droid.Resource.Id.left;
			global::XLabs.Forms.Droid.Resource.Id.left_arrow = global::JamnationApp.Droid.Resource.Id.left_arrow;
			global::XLabs.Forms.Droid.Resource.Id.line1 = global::JamnationApp.Droid.Resource.Id.line1;
			global::XLabs.Forms.Droid.Resource.Id.line3 = global::JamnationApp.Droid.Resource.Id.line3;
			global::XLabs.Forms.Droid.Resource.Id.media_actions = global::JamnationApp.Droid.Resource.Id.media_actions;
			global::XLabs.Forms.Droid.Resource.Id.normal = global::JamnationApp.Droid.Resource.Id.normal;
			global::XLabs.Forms.Droid.Resource.Id.right = global::JamnationApp.Droid.Resource.Id.right;
			global::XLabs.Forms.Droid.Resource.Id.right_arrow = global::JamnationApp.Droid.Resource.Id.right_arrow;
			global::XLabs.Forms.Droid.Resource.Id.start = global::JamnationApp.Droid.Resource.Id.start;
			global::XLabs.Forms.Droid.Resource.Id.status_bar_latest_event_content = global::JamnationApp.Droid.Resource.Id.status_bar_latest_event_content;
			global::XLabs.Forms.Droid.Resource.Id.text = global::JamnationApp.Droid.Resource.Id.text;
			global::XLabs.Forms.Droid.Resource.Id.text2 = global::JamnationApp.Droid.Resource.Id.text2;
			global::XLabs.Forms.Droid.Resource.Id.time = global::JamnationApp.Droid.Resource.Id.time;
			global::XLabs.Forms.Droid.Resource.Id.title = global::JamnationApp.Droid.Resource.Id.title;
			global::XLabs.Forms.Droid.Resource.Id.top = global::JamnationApp.Droid.Resource.Id.top;
			global::XLabs.Forms.Droid.Resource.Integer.cancel_button_image_alpha = global::JamnationApp.Droid.Resource.Integer.cancel_button_image_alpha;
			global::XLabs.Forms.Droid.Resource.Integer.status_bar_notification_info_maxnum = global::JamnationApp.Droid.Resource.Integer.status_bar_notification_info_maxnum;
			global::XLabs.Forms.Droid.Resource.Layout.calendar_pager = global::JamnationApp.Droid.Resource.Layout.calendar_pager;
			global::XLabs.Forms.Droid.Resource.Layout.calendar_pager_layout = global::JamnationApp.Droid.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Droid.Resource.Layout.calendar_picker = global::JamnationApp.Droid.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Droid.Resource.Layout.dialog = global::JamnationApp.Droid.Resource.Layout.dialog;
			global::XLabs.Forms.Droid.Resource.Layout.month = global::JamnationApp.Droid.Resource.Layout.month;
			global::XLabs.Forms.Droid.Resource.Layout.notification_media_action = global::JamnationApp.Droid.Resource.Layout.notification_media_action;
			global::XLabs.Forms.Droid.Resource.Layout.notification_media_cancel_action = global::JamnationApp.Droid.Resource.Layout.notification_media_cancel_action;
			global::XLabs.Forms.Droid.Resource.Layout.notification_template_big_media = global::JamnationApp.Droid.Resource.Layout.notification_template_big_media;
			global::XLabs.Forms.Droid.Resource.Layout.notification_template_big_media_narrow = global::JamnationApp.Droid.Resource.Layout.notification_template_big_media_narrow;
			global::XLabs.Forms.Droid.Resource.Layout.notification_template_media = global::JamnationApp.Droid.Resource.Layout.notification_template_media;
			global::XLabs.Forms.Droid.Resource.Layout.notification_template_part_chronometer = global::JamnationApp.Droid.Resource.Layout.notification_template_part_chronometer;
			global::XLabs.Forms.Droid.Resource.Layout.notification_template_part_time = global::JamnationApp.Droid.Resource.Layout.notification_template_part_time;
			global::XLabs.Forms.Droid.Resource.Layout.week = global::JamnationApp.Droid.Resource.Layout.week;
			global::XLabs.Forms.Droid.Resource.String.ApplicationName = global::JamnationApp.Droid.Resource.String.ApplicationName;
			global::XLabs.Forms.Droid.Resource.String.Hello = global::JamnationApp.Droid.Resource.String.Hello;
			global::XLabs.Forms.Droid.Resource.String.day_name_format = global::JamnationApp.Droid.Resource.String.day_name_format;
			global::XLabs.Forms.Droid.Resource.String.full_date_format = global::JamnationApp.Droid.Resource.String.full_date_format;
			global::XLabs.Forms.Droid.Resource.String.invalid_date = global::JamnationApp.Droid.Resource.String.invalid_date;
			global::XLabs.Forms.Droid.Resource.String.library_name = global::JamnationApp.Droid.Resource.String.library_name;
			global::XLabs.Forms.Droid.Resource.String.month_name_format = global::JamnationApp.Droid.Resource.String.month_name_format;
			global::XLabs.Forms.Droid.Resource.String.status_bar_notification_info_overflow = global::JamnationApp.Droid.Resource.String.status_bar_notification_info_overflow;
			global::XLabs.Forms.Droid.Resource.Style.CalendarCell = global::JamnationApp.Droid.Resource.Style.CalendarCell;
			global::XLabs.Forms.Droid.Resource.Style.CalendarCell_CalendarDate = global::JamnationApp.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Droid.Resource.Style.CalendarCell_DayHeader = global::JamnationApp.Droid.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Droid.Resource.Style.CalendarTitle = global::JamnationApp.Droid.Resource.Style.CalendarTitle;
			global::XLabs.Platform.Resource.String.ApplicationName = global::JamnationApp.Droid.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::JamnationApp.Droid.Resource.String.Hello;
			global::ZXing.Net.Mobile.Forms.Android.Resource.Layout.zxingscanneractivitylayout = global::JamnationApp.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Net.Mobile.Forms.Android.Resource.Layout.zxingscannerfragmentlayout = global::JamnationApp.Droid.Resource.Layout.zxingscannerfragmentlayout;
			global::ZXing.Net.Mobile.Forms.Android.Resource.String.library_name = global::JamnationApp.Droid.Resource.String.library_name;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::JamnationApp.Droid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::JamnationApp.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::JamnationApp.Droid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010021
			public const int ahBarColor = 2130772001;
			
			// aapt resource value: 0x7f010029
			public const int ahBarLength = 2130772009;
			
			// aapt resource value: 0x7f010028
			public const int ahBarWidth = 2130772008;
			
			// aapt resource value: 0x7f010026
			public const int ahCircleColor = 2130772006;
			
			// aapt resource value: 0x7f010025
			public const int ahDelayMillis = 2130772005;
			
			// aapt resource value: 0x7f010027
			public const int ahRadius = 2130772007;
			
			// aapt resource value: 0x7f010022
			public const int ahRimColor = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int ahRimWidth = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int ahSpinSpeed = 2130772004;
			
			// aapt resource value: 0x7f01001e
			public const int ahText = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int ahTextColor = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int ahTextSize = 2130772000;
			
			// aapt resource value: 0x7f01000c
			public const int circleColor = 2130771980;
			
			// aapt resource value: 0x7f01001d
			public const int circularProgressBarStyle = 2130771997;
			
			// aapt resource value: 0x7f010015
			public const int circular_gravity = 2130771989;
			
			// aapt resource value: 0x7f01001b
			public const int circular_indeterminate = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int circular_indeterminate_interval = 2130771996;
			
			// aapt resource value: 0x7f010018
			public const int circular_marker_progress = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int circular_progress = 2130771991;
			
			// aapt resource value: 0x7f01001a
			public const int circular_progress_background_color = 2130771994;
			
			// aapt resource value: 0x7f010019
			public const int circular_progress_color = 2130771993;
			
			// aapt resource value: 0x7f010016
			public const int circular_stroke_width = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			// aapt resource value: 0x7f010013
			public const int indeterminate = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int indeterminate_interval = 2130771988;
			
			// aapt resource value: 0x7f010011
			public const int innerSize = 2130771985;
			
			// aapt resource value: 0x7f01000b
			public const int max = 2130771979;
			
			// aapt resource value: 0x7f010012
			public const int pinned = 2130771986;
			
			// aapt resource value: 0x7f01000e
			public const int pinnedDrawable = 2130771982;
			
			// aapt resource value: 0x7f01000a
			public const int progress = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int progressButtonStyle = 2130771977;
			
			// aapt resource value: 0x7f01000d
			public const int progressColor = 2130771981;
			
			// aapt resource value: 0x7f010010
			public const int shadowDrawable = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int unpinnedDrawable = 2130771983;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0a0000
			public const int abc_action_bar_embed_tabs = 2131361792;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_active_month_bg = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int calendar_bg = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int calendar_divider = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int calendar_highlighted_day_bg = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int calendar_inactive_month_bg = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_selected_day_bg = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int calendar_selected_range_bg = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int calendar_text_active = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int calendar_text_inactive = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int calendar_text_selected = 2131099657;
			
			// aapt resource value: 0x7f060034
			public const int calendar_text_selector = 2131099700;
			
			// aapt resource value: 0x7f06000a
			public const int calendar_text_unselectable = 2131099658;
			
			// aapt resource value: 0x7f060032
			public const int entry_background = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int entry_border = 2131099699;
			
			// aapt resource value: 0x7f06000e
			public const int notification_action_color_filter = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int notification_icon_bg_color = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int notification_material_background_media_default_color = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int primary_text_default_material_dark = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int progress_default_circle_color = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int progress_default_progress_color = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int refractored_background_dark = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int refractored_background_holo_dark = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int refractored_background_holo_light = 2131099674;
			
			// aapt resource value: 0x7f060015
			public const int refractored_background_light = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int refractored_bright_foreground_dark = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int refractored_bright_foreground_dark_disabled = 2131099672;
			
			// aapt resource value: 0x7f06001d
			public const int refractored_bright_foreground_disabled_holo_dark = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int refractored_bright_foreground_disabled_holo_light = 2131099678;
			
			// aapt resource value: 0x7f06001b
			public const int refractored_bright_foreground_holo_dark = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int refractored_bright_foreground_holo_light = 2131099676;
			
			// aapt resource value: 0x7f060017
			public const int refractored_bright_foreground_light = 2131099671;
			
			// aapt resource value: 0x7f060020
			public const int refractored_dim_foreground_disabled_holo_dark = 2131099680;
			
			// aapt resource value: 0x7f060023
			public const int refractored_dim_foreground_disabled_holo_light = 2131099683;
			
			// aapt resource value: 0x7f06001f
			public const int refractored_dim_foreground_holo_dark = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int refractored_dim_foreground_holo_light = 2131099682;
			
			// aapt resource value: 0x7f060025
			public const int refractored_highlighted_text_holo_dark = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int refractored_highlighted_text_holo_light = 2131099686;
			
			// aapt resource value: 0x7f060021
			public const int refractored_hint_foreground_holo_dark = 2131099681;
			
			// aapt resource value: 0x7f060024
			public const int refractored_hint_foreground_holo_light = 2131099684;
			
			// aapt resource value: 0x7f060030
			public const int refractored_holo_blue_bright = 2131099696;
			
			// aapt resource value: 0x7f06002a
			public const int refractored_holo_blue_dark = 2131099690;
			
			// aapt resource value: 0x7f060027
			public const int refractored_holo_blue_light = 2131099687;
			
			// aapt resource value: 0x7f06002b
			public const int refractored_holo_green_dark = 2131099691;
			
			// aapt resource value: 0x7f060028
			public const int refractored_holo_green_light = 2131099688;
			
			// aapt resource value: 0x7f06002f
			public const int refractored_holo_orange_dark = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public const int refractored_holo_orange_light = 2131099694;
			
			// aapt resource value: 0x7f06002d
			public const int refractored_holo_purple = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int refractored_holo_red_dark = 2131099692;
			
			// aapt resource value: 0x7f060029
			public const int refractored_holo_red_light = 2131099689;
			
			// aapt resource value: 0x7f060010
			public const int ripple_material_light = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int secondary_text_default_material_dark = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int secondary_text_default_material_light = 2131099665;
			
			// aapt resource value: 0x7f060031
			public const int splash_background = 2131099697;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int calendar_day_headers_paddingbottom = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int calendar_month_title_bottommargin = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int calendar_month_topmargin = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int calendar_text_medium = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int calendar_text_small = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int compat_button_inset_horizontal_material = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int compat_button_inset_vertical_material = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int compat_button_padding_horizontal_material = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int compat_button_padding_vertical_material = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int compat_control_corner_material = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int notification_action_icon_size = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int notification_action_text_size = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int notification_big_circle_margin = 2131165200;
			
			// aapt resource value: 0x7f070006
			public const int notification_content_margin_start = 2131165190;
			
			// aapt resource value: 0x7f070011
			public const int notification_large_icon_height = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int notification_large_icon_width = 2131165202;
			
			// aapt resource value: 0x7f070007
			public const int notification_main_column_padding_top = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int notification_media_narrow_margin = 2131165192;
			
			// aapt resource value: 0x7f070013
			public const int notification_right_icon_size = 2131165203;
			
			// aapt resource value: 0x7f070005
			public const int notification_right_side_padding_top = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int notification_small_icon_background_padding = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int notification_small_icon_size_as_large = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int notification_subtext_size = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int notification_top_pad = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int notification_top_pad_large_text = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int progress_inner_size = 2131165209;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AddPhoto = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int calendar_bg_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int call = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int clock = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int CloseButtons = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int details = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int filter = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int friends = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int guy = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int hamburger = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int history = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int home = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_errorstatus = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_successstatus = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Icon_Inverse = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int info = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int interests = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int left = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int left_white = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int list = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int list_yellow = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int location = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int location_yellow = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int logo = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int logo_inverse = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int map = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int message = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int monkey = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int musiclibrary = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int myprofile = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Nearby = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int notification_action_background = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int notification_bg = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int notification_bg_low = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int notification_bg_low_normal = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int notification_bg_low_pressed = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int notification_bg_normal = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int notification_bg_normal_pressed = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int notification_icon_background = 2130837545;
			
			// aapt resource value: 0x7f02004a
			public const int notification_template_icon_bg = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int notification_template_icon_low_bg = 2130837579;
			
			// aapt resource value: 0x7f02002a
			public const int notification_tile_bg = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int notify_panel_notification_icon_bg = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int pencil = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int photos = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int pin = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int pin_progress_pinned = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int pin_progress_shadow = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int pin_progress_unpinned = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int places = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int right = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int right_white = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int roundedbg = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int roundedbgdark = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int scrubber_control_normal_holo = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int scrubber_control_pressed_holo = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int search = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int settings = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int splash_screen = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int Test1 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int Test2 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int Test3 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int unknown = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int unknown_female = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int unknown_male = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int welcome1 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int welcome1bar = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int welcome2 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int welcome2bar = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int welcome3 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int welcome3bar = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int welcome4bar = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int xamarin = 2130837577;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0024
			public const int InfoWindowButton = 2131427364;
			
			// aapt resource value: 0x7f0b0023
			public const int InfoWindowSubtitle = 2131427363;
			
			// aapt resource value: 0x7f0b0022
			public const int InfoWindowTitle = 2131427362;
			
			// aapt resource value: 0x7f0b0029
			public const int action0 = 2131427369;
			
			// aapt resource value: 0x7f0b0026
			public const int action_container = 2131427366;
			
			// aapt resource value: 0x7f0b002d
			public const int action_divider = 2131427373;
			
			// aapt resource value: 0x7f0b0027
			public const int action_image = 2131427367;
			
			// aapt resource value: 0x7f0b0028
			public const int action_text = 2131427368;
			
			// aapt resource value: 0x7f0b0037
			public const int actions = 2131427383;
			
			// aapt resource value: 0x7f0b0006
			public const int async = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int blocking = 2131427335;
			
			// aapt resource value: 0x7f0b000b
			public const int bottom = 2131427339;
			
			// aapt resource value: 0x7f0b0025
			public const int calendar_grid = 2131427365;
			
			// aapt resource value: 0x7f0b001b
			public const int calendar_view = 2131427355;
			
			// aapt resource value: 0x7f0b001a
			public const int calendarr_pager = 2131427354;
			
			// aapt resource value: 0x7f0b002a
			public const int cancel_action = 2131427370;
			
			// aapt resource value: 0x7f0b000c
			public const int center = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int center_horizontal = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int center_vertical = 2131427342;
			
			// aapt resource value: 0x7f0b0032
			public const int chronometer = 2131427378;
			
			// aapt resource value: 0x7f0b000f
			public const int clip = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int clip_horizontal = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int clip_vertical = 2131427345;
			
			// aapt resource value: 0x7f0b003a
			public const int contentFrame = 2131427386;
			
			// aapt resource value: 0x7f0b0012
			public const int end = 2131427346;
			
			// aapt resource value: 0x7f0b0039
			public const int end_padder = 2131427385;
			
			// aapt resource value: 0x7f0b0013
			public const int fill = 2131427347;
			
			// aapt resource value: 0x7f0b0014
			public const int fill_horizontal = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public const int fill_vertical = 2131427349;
			
			// aapt resource value: 0x7f0b0008
			public const int forever = 2131427336;
			
			// aapt resource value: 0x7f0b0034
			public const int icon = 2131427380;
			
			// aapt resource value: 0x7f0b0038
			public const int icon_group = 2131427384;
			
			// aapt resource value: 0x7f0b0033
			public const int info = 2131427379;
			
			// aapt resource value: 0x7f0b0009
			public const int italic = 2131427337;
			
			// aapt resource value: 0x7f0b0016
			public const int left = 2131427350;
			
			// aapt resource value: 0x7f0b001d
			public const int left_arrow = 2131427357;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b0020
			public const int loadingImage = 2131427360;
			
			// aapt resource value: 0x7f0b001e
			public const int loadingProgressBar = 2131427358;
			
			// aapt resource value: 0x7f0b0021
			public const int loadingProgressWheel = 2131427361;
			
			// aapt resource value: 0x7f0b002c
			public const int media_actions = 2131427372;
			
			// aapt resource value: 0x7f0b000a
			public const int normal = 2131427338;
			
			// aapt resource value: 0x7f0b0036
			public const int notification_background = 2131427382;
			
			// aapt resource value: 0x7f0b002f
			public const int notification_main_column = 2131427375;
			
			// aapt resource value: 0x7f0b002e
			public const int notification_main_column_container = 2131427374;
			
			// aapt resource value: 0x7f0b0017
			public const int right = 2131427351;
			
			// aapt resource value: 0x7f0b001c
			public const int right_arrow = 2131427356;
			
			// aapt resource value: 0x7f0b0035
			public const int right_icon = 2131427381;
			
			// aapt resource value: 0x7f0b0030
			public const int right_side = 2131427376;
			
			// aapt resource value: 0x7f0b0018
			public const int start = 2131427352;
			
			// aapt resource value: 0x7f0b002b
			public const int status_bar_latest_event_content = 2131427371;
			
			// aapt resource value: 0x7f0b0002
			public const int tag_transition_group = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int text2 = 2131427332;
			
			// aapt resource value: 0x7f0b001f
			public const int textViewStatus = 2131427359;
			
			// aapt resource value: 0x7f0b0031
			public const int time = 2131427377;
			
			// aapt resource value: 0x7f0b0005
			public const int title = 2131427333;
			
			// aapt resource value: 0x7f0b0019
			public const int top = 2131427353;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int cancel_button_image_alpha = 2131296256;
			
			// aapt resource value: 0x7f090003
			public const int circular_indeterminent_interval = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int progressbutton_indeterminent_interval = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int status_bar_notification_info_maxnum = 2131296257;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_pager_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int calendar_picker = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loading = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int loadingimage = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loadingprogress = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MapInfoWindow = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int month = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_action = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_action_tombstone = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_media_action = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_media_cancel_action = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_big_media = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_big_media_custom = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_big_media_narrow = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_big_media_narrow_custom = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int notification_template_custom_big = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int notification_template_icon_group = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int notification_template_lines_media = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int notification_template_media = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int notification_template_media_custom = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int notification_template_part_chronometer = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int notification_template_part_time = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int RoundedCornerEntry = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int week = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int XamarinMapInfoWindow = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int zxingscanneractivitylayout = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int zxingscannerfragmentlayout = 2130903068;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int rootcert = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int app_name = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int day_name_format = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int full_date_format = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int invalid_date = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int month_name_format = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int status_bar_notification_info_overflow = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int CalendarCell = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int CalendarCell_CalendarDate = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int CalendarCell_DayHeader = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int CalendarTitle = 2131230720;
			
			// aapt resource value: 0x7f080012
			public const int CircularProgressBar = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int CircularProgressBarLight = 2131230739;
			
			// aapt resource value: 0x7f080010
			public const int ProgressButton = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int ProgressButton_Pin = 2131230737;
			
			// aapt resource value: 0x7f080009
			public const int TextAppearance_Compat_Notification = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int TextAppearance_Compat_Notification_Info = 2131230730;
			
			// aapt resource value: 0x7f080004
			public const int TextAppearance_Compat_Notification_Info_Media = 2131230724;
			
			// aapt resource value: 0x7f08000f
			public const int TextAppearance_Compat_Notification_Line2 = 2131230735;
			
			// aapt resource value: 0x7f080008
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int TextAppearance_Compat_Notification_Media = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int TextAppearance_Compat_Notification_Time = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Time_Media = 2131230726;
			
			// aapt resource value: 0x7f08000c
			public const int TextAppearance_Compat_Notification_Title = 2131230732;
			
			// aapt resource value: 0x7f080007
			public const int TextAppearance_Compat_Notification_Title_Media = 2131230727;
			
			// aapt resource value: 0x7f080014
			public const int Theme_Splash = 2131230740;
			
			// aapt resource value: 0x7f08000d
			public const int Widget_Compat_NotificationActionContainer = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int Widget_Compat_NotificationActionText = 2131230734;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			public static int[] HoloCircularProgressBar = new int[] {
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int HoloCircularProgressBar_circular_gravity = 0;
			
			// aapt resource value: 6
			public const int HoloCircularProgressBar_circular_indeterminate = 6;
			
			// aapt resource value: 7
			public const int HoloCircularProgressBar_circular_indeterminate_interval = 7;
			
			// aapt resource value: 3
			public const int HoloCircularProgressBar_circular_marker_progress = 3;
			
			// aapt resource value: 2
			public const int HoloCircularProgressBar_circular_progress = 2;
			
			// aapt resource value: 5
			public const int HoloCircularProgressBar_circular_progress_background_color = 5;
			
			// aapt resource value: 4
			public const int HoloCircularProgressBar_circular_progress_color = 4;
			
			// aapt resource value: 1
			public const int HoloCircularProgressBar_circular_stroke_width = 1;
			
			public static int[] ProgressButton = new int[] {
					16842970,
					16842981,
					16843534,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 1
			public const int ProgressButton_android_clickable = 1;
			
			// aapt resource value: 0
			public const int ProgressButton_android_focusable = 0;
			
			// aapt resource value: 2
			public const int ProgressButton_android_selectableItemBackground = 2;
			
			// aapt resource value: 5
			public const int ProgressButton_circleColor = 5;
			
			// aapt resource value: 12
			public const int ProgressButton_indeterminate = 12;
			
			// aapt resource value: 13
			public const int ProgressButton_indeterminate_interval = 13;
			
			// aapt resource value: 10
			public const int ProgressButton_innerSize = 10;
			
			// aapt resource value: 4
			public const int ProgressButton_max = 4;
			
			// aapt resource value: 11
			public const int ProgressButton_pinned = 11;
			
			// aapt resource value: 7
			public const int ProgressButton_pinnedDrawable = 7;
			
			// aapt resource value: 3
			public const int ProgressButton_progress = 3;
			
			// aapt resource value: 6
			public const int ProgressButton_progressColor = 6;
			
			// aapt resource value: 9
			public const int ProgressButton_shadowDrawable = 9;
			
			// aapt resource value: 8
			public const int ProgressButton_unpinnedDrawable = 8;
			
			public static int[] ProgressWheel = new int[] {
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			public static int[] Theme = new int[] {
					2130771997};
			
			// aapt resource value: 0
			public const int Theme_circularProgressBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
